In [40]:
# importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import label_binarize

# importing the dataset
iris = load_iris()
data = pd.DataFrame(iris.data, columns=iris.feature_names)
data['Species'] = iris.target
data.sample(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
55                 5.7               2.8                4.5               1.3   
62                 6.0               2.2                4.0               1.0   
119                6.0               2.2                5.0               1.5   
29                 4.7               3.2                1.6               0.2   
10                 5.4               3.7                1.5               0.2   
92                 5.8               2.6                4.0               1.2   
81                 5.5               2.4                3.7               1.0   
122                7.7               2.8                6.7               2.0   
9                  4.9               3.1                1.5               0.1   
54                 6.5               2.8                4.6               1.5   

     Species  
55         1  
62         1  
119        2  
29         0  
10         0  
92         1  
81         1  
122        2  
9          0  
54         1

In [41]:
#Iris-setosa = 0 and Iris-virginica/Iris-versicolour = 1
le = LabelEncoder()
le.fit(["Iris-setosa", "Iris-virginica", "Iris-versicolour"])

LabelEncoder()

In [42]:
list(le.classes_)

['Iris-setosa', 'Iris-versicolour', 'Iris-virginica']

In [43]:
le.transform(["Iris-setosa", "Iris-virginica", "Iris-versicolour"])
#array([0, 2, 1])
#I need the non-setosa classes to all fall into one number

array([0, 2, 1])

In [44]:
label_binarize(["Iris-setosa", "Iris-virginica", "Iris-versicolour"], classes=["Iris-setosa"])
#showing me the reverse of what i want

array([[1],
       [0],
       [0]])

In [48]:
#i know that in the data, 0 = setosa, so I add a column isSetosa, if species > 0, it is not setosa so set to 1 (greather than 0 is true)
data['isSetosa'] = data['Species'].gt(0).astype(int)
data.sample(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
148                6.2               3.4                5.4               2.3   
27                 5.2               3.5                1.5               0.2   
100                6.3               3.3                6.0               2.5   
24                 4.8               3.4                1.9               0.2   
33                 5.5               4.2                1.4               0.2   
15                 5.7               4.4                1.5               0.4   
50                 7.0               3.2                4.7               1.4   
105                7.6               3.0                6.6               2.1   
64                 5.6               2.9                3.6               1.3   
108                6.7               2.5                5.8               1.8   

     Species  isSetosa  
148        2         1  
27         0         0  
100        2         1  
24         0         0  
33         0         0  
15         0         0  
50         1         1  
105        2         1  
64         1         1  
108        2         1

In [47]:
data['isSetosa'] = iris.target
data.sample(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
57                 4.9               2.4                3.3               1.0   
42                 4.4               3.2                1.3               0.2   
102                7.1               3.0                5.9               2.1   
33                 5.5               4.2                1.4               0.2   
139                6.9               3.1                5.4               2.1   
53                 5.5               2.3                4.0               1.3   
78                 6.0               2.9                4.5               1.5   
36                 5.5               3.5                1.3               0.2   
41                 4.5               2.3                1.3               0.3   
134                6.1               2.6                5.6               1.4   

     Species  isSetosa  
57         1         1  
42         0         0  
102        2         2  
33         0         0  
139        2         2  
53         1         1  
78         1         1  
36         0         0  
41         0         0  
134        2         2

In [49]:
data['isSetosa'] = iris.target_names
data.sample(10)

ValueError: Length of values (3) does not match length of index (150)